### ISSUE TITLE
[Feature] Support `.yml` extension for `chainsaw-test` file

### ISSUE THREAD

**Issue by chipzoller** [kyverno/chainsaw#1003]
### Problem Statement

Chainsaw will ONLY look for a file named `chainsaw-test.yaml` including the hard dependency on the `.yaml` extension. YAML files can also have an extension of `.yml` but Chainsaw will not find these files.

### Solution Description

Chainsaw should look for `chainsaw-test.yaml` OR `chainsaw-test.yml`.

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
What should happen if both are present ?

**Comment by chipzoller** [comment]
Search order is .yaml followed by .yml
