### ISSUE TITLE
[Bug] chainsaw migrate kuttl config prints diagnostics to stdout

### ISSUE THREAD

**Issue by porridge** [kyverno/chainsaw#1092]
### chainsaw version Version

v0.1.8

### Description

```
$ chainsaw migrate kuttl config kuttl-test.yaml > chainsaw.yaml
$ head -n 1 chainsaw.yaml
Converting config kuttl-test.yaml ...
$
```

### Steps to reproduce

See above.

### Expected behavior

I'd expect the `Converting...` message to go to stderr. Combining it with stdout produces invalid YAML.

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
Good catch, i didn't think about this way of using it 🤷

**Comment by eddycharly** [comment]
BTW, happy to see you trying out chainsaw ;)

**Comment by eddycharly** [comment]
Thanks for reporting, will be fixed in the next release.
