### ISSUE TITLE
[Feature] use environment variables in tests

### ISSUE THREAD

**Issue by eljohnson92** [kyverno/chainsaw#1111]
### Problem Statement

I'm not sure if this is already possible but we would like to be able to reference environment variables in our tests in order to inject some environment unique information into our tests.

### Solution Description

we would like a way to reference environment variables from within chainsaw tests so we can make resource names more unique by using something such as a git commit to prefix resources with.

### Alternatives

we could use the pipe to values notation documented [here](https://kyverno.github.io/chainsaw/latest/configuration/values/#example) but it would be nice if we could just reference variables from within tests

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
i.e `name: (join('-', [env(FOO), env(BAR)]))`
