### ISSUE TITLE
[Feature] Use wait command with jsonpath

### ISSUE THREAD

**Issue by Raazor** [kyverno/chainsaw#1146]
### Problem Statement

For testing against different CRDs conditions might often not be available, but waiting for arbitrary json paths is possible.

### Solution Description

Enhance the wait functionality wrapper to also enable users to enter a json path and wrap this kubectl functionality:
 kubectl wait --for=jsonpath='{path}'=value resourcetype/resourcename -n namespace

Example (showing my current use case) :
        - wait:
          #....
            for:
              jsonpath:
                path: status.statuses.gloo-system.state
                value: 'Accepted'

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
Thanks for the feature request, i'm going to add this to the next release.

**Comment by Raazor** [comment]
It's really awesome to see how quickly you are reacting to these requests ! :-)

Since I am currently developing against the main version I already tested it, because then we could go on without installing kubectl even. Unfortunately I ran into an error with the implementation.
I will post the output here as screenshots - failing being with implemented wait functionality (hostedtoolchain -> kubectl) and working with running kubectl command wrapped in chainsaw script (running from /usr/bin/sh).
Anyhow, still great development progress ! 
![wait_jsonpath_error_1](https://github.com/kyverno/chainsaw/assets/9135461/88dd8139-60d7-4f75-9026-bd0dfcbb268a)
![wait_jsonpath_error_2](https://github.com/kyverno/chainsaw/assets/9135461/ea97cd67-5a3d-43ca-b682-1b6e632e710b)

**Comment by eddycharly** [comment]
Hmm, this happens because there's some shell expansion going on :(

**Comment by eddycharly** [comment]
This should fix your issue https://github.com/kyverno/chainsaw/pull/1170 🤞

**Comment by Raazor** [comment]
Confirmed working. 
Awesome, Thanks !  💯
