### ISSUE TITLE
[Question] Couldn't Find Documentation for Built-in Bindings List

### ISSUE THREAD

**Issue by emirsaidh** [kyverno/chainsaw#1242]
### Describe your question

I've been exploring the Kyverno project and came across the usage of a built-in binding in the testdata/e2e/examples/k8s-server-version directory, as mentioned in the [documentation](https://kyverno.github.io/chainsaw/latest/bindings/). However, I couldn't find a comprehensive list of built-in bindings to reference. I've searched through the documentation, but it seems to be missing.

Issue:
It would be immensely helpful for users like me to have access to a centralized list of all built-in bindings available in Kyverno, along with their descriptions and usage examples. This would streamline the learning process and enable us to leverage Kyverno's capabilities more effectively.

Suggestion:
I propose adding a dedicated section to the documentation that lists all built-in bindings, providing clear descriptions and usage examples for each one. This would enhance the usability of Kyverno and contribute to a better overall user experience.

How I Can Help:
If this feature is not yet available, I would like to contribute by helping to create this documentation. Please let me know if there's anything specific I can do to assist in this process.

### chainsaw version Version

v0.1.9

**Comment by eddycharly** [comment]
Thanks for asking the question, this is fixed in https://github.com/kyverno/chainsaw/pull/1413
