### ISSUE TITLE
Add more in the Community section of the website

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#1314]
We can take inspiration from:
https://squidfunk.github.io/mkdocs-material/contributing/

**Comment by Manoramsharma** [comment]
Hi @eddycharly, Taking reference from the mentioned documentation I can generate the sections like contributing, reporting issues, making a PR and some more based on my observation should I move forward?

**Comment by eddycharly** [comment]
@Manoramsharma it would be awesome !
