### ISSUE TITLE
How to access key in binding that contains '-' 

### ISSUE THREAD

**Issue by markussiebert** [kyverno/chainsaw#1347]
### Describe your question

I have values in a binding like:
```json
{
  "resources": {
    "some-key": "some-value"
}}
```
and I want to access it like:

name: ($resolved_resources.resources.some-key)

in an assertion, but it does not work. 

neither do
name: ($resolved_resources.resources[some-key])
or
name: ($resolved_resources.resources."some-key")

Any ideas?

### chainsaw version Version

v0.1.0

**Comment by eddycharly** [comment]
I think `$resolved_resources.resources."some-key"` should be the correct syntax.

Can you post a simple example to reproduce the issue ?

**Comment by markussiebert** [comment]
no, it isn't - chainsaw complains about. I switched to providing the values as array and do queries like:
```
 ($resolved_resources.resources[?compositionResourceName == 'someresource'].resourceName | [0])
 ```

**Comment by eddycharly** [comment]
Ok, still if you have a simple example to reproduce i would be interested in seeing if this can be improved.

**Comment by eddycharly** [comment]
Closing, not enough info to reproduce.
