### ISSUE TITLE
[Question] Error operator - How to use to also specify expected type of error ?

### ISSUE THREAD

**Issue by Raazor** [kyverno/chainsaw#1352]
### Describe your question

When going through the description of the "Error" Operator I find exactly what I am currently looking for. Basically I do not only want to assert that an error is happening when I apply a certain resource but also what kind of error. 
`
DEFINITION:The error operation lets you define a set of expected errors for a test step. If any of these errors occur during the test, they are treated as expected outcomes. However, if an error that's not on this list occurs, it will be treated as a test failure.
`

However, I do not know how to use it this way. How it currently works for me is like this: 
```yaml
  - name: Validate policy error case
    try:
      - error:
          file: "./tests/*-invalid.yaml"
```
In this case the *-invalid.yaml files are resources that go against a defined kyverno cluster policy. So I would think that the error operator in this case applys the file referenced resource and expects an error, which is not explicitely what is described by the definition above in my opinion.
What I would like to do in this step is to apply these *-invalid.yaml files and assert that "PolicyViolation" errors are thrown. How can this be done ? 

Thank you and best regards.

Martin

### chainsaw version Version

v0.2.0

**Comment by eddycharly** [comment]
```yaml
      - error:
          file: "./tests/*-invalid.yaml"
```

This doesn't apply anything, to put it simply, `error` is the opposite of `assert`.

You can achieve what you want with something like this:

```yaml
      - apply:
          file: "./tests/*-invalid.yaml"
          expect:
          - check:
              ($error): whatever error message comes here
```

**Comment by eddycharly** [comment]
@Raazor check [this page](https://kyverno.github.io/chainsaw/main/quick-start/advanced/negative-testing/) and let me know if it helps.

**Comment by Raazor** [comment]
> @Raazor check [this page](https://kyverno.github.io/chainsaw/main/quick-start/advanced/negative-testing/) and let me know if it helps.

Thanks, that is exactly what I was looking for :) 

My error message is very long however, and I cannot get it to work with a complete match of the error, it was rather be nice to see if the error messages contains something like "validation error: externalIPs are not allowed" or so, here is an example message :

```
admission webhook "validate.kyverno.svc-ignore" denied the request:

        resource Service/chainsaw-real-lemur/badservice02 was blocked due to the following policies

        restrict-external-ips:
          check-ips: 'validation error: externalIPs are not allowed. Policy Link: https://asdf.asdf.asdf/policy.yaml.
            rule check-ips failed at path /spec/externalIPs/'
```

I will just use the apply with the check and ($error != null): true, and then check for a PolicyViolation event in the next step. It's gonna be a bit more effort but it is the only way I see now. Feel free to share if you have another idea, but otherwise thank you a lot for your help ! 👍

**Comment by eddycharly** [comment]
Look at this https://kyverno.github.io/chainsaw/main/quick-start/advanced/test-output/ you can use functions like `contains` or `wildcard` to do pattern matching on the error message.

Please, close the issue if you consider it solved 🙏

**Comment by Raazor** [comment]
Awesome :) Thanks !! 💯
