### ISSUE TITLE
Is it possible to use system environment variable in bindings or operations (apply ..etc)

### ISSUE THREAD

**Issue by vinish86** [kyverno/chainsaw#1830]
### Describe your question

I would like to use a system environment variable in the test, especially under binding. I've referred to the [issue](https://github.com/kyverno/chainsaw/issues/1111) and followed the suggested format in the comments, but it's failing with an error.
`=== ERROR
        <nil>: Internal error: invalid type for: <nil>, expected: []functions.JpType{"string"}`
 
  bindings:
  - name: branchName
    value: (env(BRANCH_NAME))

    
    

### chainsaw version Version

v0.2.7

**Comment by eddycharly** [comment]
Yes, you need to put the env var name into single quotes: `value: (env('BRANCH_NAME'))`

**Comment by eddycharly** [comment]
@vinish86 did it fix your issue ?

**Comment by eddycharly** [comment]
Closing as it was answered, please reopen if needed.
