### ISSUE TITLE
[Bug] Go 1.23 incompatibility

### ISSUE THREAD

**Issue by evenh** [kyverno/chainsaw#1869]
### chainsaw version Version

v0.2.8

### Description

When [upgrading a project to use Go 1.23 ](https://github.com/kartverket/skiperator/pull/512) it fails with the following compile error:
```
Error: ../../../go/pkg/mod/github.com/kyverno/chainsaw@v0.2.8/pkg/runner/run.go:72:25: cannot use deps (variable of type *"github.com/kyverno/chainsaw/pkg/runner/internal".TestDeps) as "testing".testDeps value in argument to testing.MainStart: *"github.com/kyverno/chainsaw/pkg/runner/internal".TestDeps does not implement "testing".testDeps (missing method InitRuntimeCoverage)
```

### Steps to reproduce

1. Checkout chainsaw at `v0.2.8` (7bd4223d)
2. Upgrade the local installation of Go to v1.23
3. Run `make tests`
4. Observe the following output:
    ```
    Create package shim...
    Generate conversion functions...
    Generate deep copy functions...
    Generate registration...
    Generate crds...
    Copy generated CRDs to embed in the CLI...
    Go fmt...
    Go vet...
    # github.com/kyverno/chainsaw/pkg/runner
    pkg/runner/run.go:72:25: cannot use deps (variable of type *"github.com/kyverno/chainsaw/pkg/runner/internal".TestDeps) as "testing".testDeps value in argument to testing.MainStart: *"github.com/kyverno/chainsaw/pkg/runner/internal".TestDeps does not implement "testing".testDeps (missing method InitRuntimeCoverage)
    # github.com/kyverno/chainsaw/pkg/runner
    # [github.com/kyverno/chainsaw/pkg/runner]
    vet: pkg/runner/run.go:72:25: cannot use deps (variable of type *internal.TestDeps) as "testing".testDeps value in argument to testing.MainStart: *internal.TestDeps does not implement "testing".testDeps (missing method InitRuntimeCoverage)
    make: *** [vet] Error 1
    ```

### Expected behavior

That chainsaw would be compatible with Go 1.23. The breakage of the internal Go interface seems to be [introduced here](https://github.com/golang/go/commit/180ea45566d19e60aa2d660f6139b7f6e18ff56b#diff-36f401ff1ffadb7d7a39cf41c2329615b159fa95cf2e14c1f58d8c46331af429R208).

### Slack discussion

https://kubernetes.slack.com/archives/C067LUFL43U/p1724065503802909

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
Thanks for reporting.
