### ISSUE TITLE
[Feature] extend expression.Engine to support json values

### ISSUE THREAD

**Issue by nkuacac** [kyverno/chainsaw#1891]
### Problem Statement

Sometimes, some content in a spec needs to be initialized based on the environment.  
```
  spec: |
    {
        "Name": "demo-test-1",
        "NetType": "plb",
        "Zone": "($values.users[?name=='mysecret'].zone|[0])",
        "VpcId": "($values.users[?name=='mysecret'].vpc|[0])",
        "SubnetId": "($values.users[?name=='mysecret'].subnet|[0])",
        "AddressType": "PRIVATE",
        "Nodepool": "($values.node_pools[0].name)"
    }
```

### Solution Description

extend expression.Engine json
```  
spec: |
    (json:{
        "Name": "demo-test-1",
        "NetType": "plb",
        "Zone": "($values.users[?name=='mysecret'].zone|[0])",
        "VpcId": "($values.users[?name=='mysecret'].vpc|[0])",
        "SubnetId": "($values.users[?name=='mysecret'].subnet|[0])",
        "AddressType": "PRIVATE",
        "Nodepool": "($values.node_pools[0].name)"
    })
```

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
You can use `to_string`.

**Comment by nkuacac** [comment]
> You can use `to_string`.

maybe my example is not good enough.  we can not use `to_string` to bind "json like string" to body.  Thanks for discuss.
``` 
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: spec-map
spec:
  template: true
  steps:
    - try:
        - script:
            bindings:
              - name: nodePool
                value: "test"
              - name: body
                value: |
                  (to_string({
                      "AddressType": "PRIVATE",
                      "Nodepool": "($nodePool)"
                  })
```

**Comment by eddycharly** [comment]
I don't get it. `to_string` will take an object and return the json string representation.
```
              - name: body
                value: (to_string({ AddressType: 'PRIVATE', Nodepool: $nodePool }))
```

**Comment by nkuacac** [comment]
> I don't get it. `to_string` will take an object and return the json string representation.
> 
> ```
>               - name: body
>                 value: (to_string({ AddressType: 'PRIVATE', Nodepool: $nodePool }))
> ```

ok , it works.  what if the json has many keys.

**Comment by eddycharly** [comment]
> what if the json has many keys

What do you mean ?

**Comment by eddycharly** [comment]
Closing, please reopen if necessary.
