### ISSUE TITLE
[Question] Test without actually deploying anything?

### ISSUE THREAD

**Issue by siredmar** [kyverno/chainsaw#1908]
### Describe your question

Hi!

I'm searching for a test tool that supports me testing my kustomize overlays in terms of: 
"What you define in your overlay matches the expected outcome."

What i basically need is:
1. It can run commands like `kustomize build ${myoverlay} > foo.yaml`
2. It compares the manifests from `foo.yaml` with some asserted resources. The minimum i need is kind, apiVersion, metadata.name and metadata.namespace. 

For this i don't need or even want deploy this anywhere.

Is this kind of setup possible with chainsaw?

### chainsaw version Version

v0.2.8

**Comment by eddycharly** [comment]
It's not possible today, I have ideas in mind to allow this kind of assertions but nothing started yet.

**Comment by siredmar** [comment]
Thanks!
