### ISSUE TITLE
[Feature] Make the Chainsaw binaries available for IBM P linux/ppc64le and IBM Z linux/s390x architectures.

### ISSUE THREAD

**Issue by IshwarKanse** [kyverno/chainsaw#1909]
### Problem Statement

We use Chainsaw to run tests on IBM P ppc64le and IBM Z s390x OpenShift clusters. It would be great if we could provide the release binaries for Chansaw which can be used for these platforms. 

### Solution Description

Build the Chainsaw release binaries for IBM P linux/ppc64le and IBM Z linux/s390x 

### Alternatives

The alternative is to clone the repo and build the binaries ourselves. 

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
@IshwarKanse do you want to open a PR ?

**Comment by eddycharly** [comment]
Trying with this https://github.com/kyverno/chainsaw/pull/1910 🤞

**Comment by IshwarKanse** [comment]
@eddycharly Thanks for adding the feature. I have asked my team members who work on the IBM platforms to check. I'll get back with the status.

**Comment by IshwarKanse** [comment]
@eddycharly The binaries are working fine. Closing this one out. Thanks :)

**Comment by eddycharly** [comment]
@IshwarKanse awesome, thanks for confirming !
