### ISSUE TITLE
[Bug] --report-name lost it's default

### ISSUE THREAD

**Issue by camaeel** [kyverno/chainsaw#1938]
### chainsaw version Version

v0.2.9

### Description

Chainsaw is not using report-name default value

### Steps to reproduce

1. Call `chainsaw test --config=config.yaml --no-color  --values=environments/${env.ENVIRONMENT}/chainsaw-values.yaml --report-format XML --report-path=. `
2. After completion it creates file `</>.xml` instead of previous (<=0.2.8) `chainsaw-report.xml`

### Expected behavior

Without passing --report-name report file should be named chainsaw-report as before.

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
Thanks for reporting, will fix asap!

**Comment by camaeel** [comment]
That was fast, thanx
