### ISSUE TITLE
[Bug] 'chainsaw build docs' does not honor end-of-file

### ISSUE THREAD

**Issue by pgmgb** [kyverno/chainsaw#2127]
### chainsaw version Version

v0.2.11

### Description

`chainsaw build docs` does not honor end-of-file - it will add two empty lines at the end of the generated `README.md`

### Steps to reproduce

Execute `chainsaw build docs --test-dir "./tests/chainsaw" --catalog ./CHAINSAW-TEST-CATALOG.md` and check the generated `README.md` for each chainsaw test. There will be two empty lines at the end instead of one.

### Expected behavior

`chainsaw build docs` honors end-of-file and adds one empty line.

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
This is very minor, please consider opening a fix PR :)
