### ISSUE TITLE
[Bug] 'chainsaw build docs' renders invalid markdown

### ISSUE THREAD

**Issue by pgmgb** [kyverno/chainsaw#2128]
### chainsaw version Version

v0.2.11

### Description

`chainsaw build docs` renders invalid markdown inside the `README.md` of each test.

### Steps to reproduce

Execute `chainsaw build docs --test-dir "./tests/chainsaw" --catalog ./CHAINSAW-TEST-CATALOG.md` and check the generated `README.md` for each chainsaw test. There will be invalid markdown inside the `Steps`.
![image](https://github.com/user-attachments/assets/0a48d13e-3b4a-43e1-bbd3-4d9c761b2941)

### Expected behavior

`chainsaw build docs --test-dir "./tests/chainsaw" --catalog ./CHAINSAW-TEST-CATALOG.md` will render valid markdown.

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
Thanks for reporting!
