### ISSUE TITLE
Refactor PodLogs to Utilize Kubernetes Client Libraries for Log Retrieval

### ISSUE THREAD

**Issue by shubham-cmyk** [kyverno/chainsaw#438]
Should we depend on kubectl here for the pod-Logs [here](https://github.com/kyverno/chainsaw/blob/main/pkg/runner/collect/pod_logs.go#L21)
or use : 
client-go to extract logs from
`/api/v1/namespaces/{namespace}/pods/{name}/log`

**Comment by shubham-cmyk** [comment]
@eddycharly

**Comment by eddycharly** [comment]
not sure it brings much value

**Comment by shubham-cmyk** [comment]
@eddycharly 
If someone use chainsaw in the github action he has to make sure that the `kubectl` is present there.
Right now we don't support create `kind` cluster but if we do that it's rare that the user would install `kubectl` in the actions.
