### ISSUE TITLE
Add useful examples

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#533]
We should provide as many examples as possible to help getting users up and running.

Please comment with examples that you would like to be added.

**Comment by jeremymv2** [comment]
Any examples of partial comparison of slices would be super useful and help the community adoption. kuttl shortcoming reference: https://github.com/kudobuilder/kuttl/issues/76

**Comment by eddycharly** [comment]
I could not agree more, i have a blog post coming and created an issue to better reflect the power of assertion trees in the docs #669

**Comment by eddycharly** [comment]
With recent PRs i think we're good.
If something is missing please add an issue or create a discussion.
