### ISSUE TITLE
Create ROADMAP

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#534]
Create ROADMAP.

**Comment by shubham-cmyk** [comment]
Some Mid Term Goals to be achieved :1st_place_medal: 
1. Adding Chainsaw to the operator SDK Testing Docs
2. Establish Community Meetings weekly or bi-weekly. 
3. Possible Create some template extension to quickly write chainsaw test. 
.... continuing more

**Comment by eddycharly** [comment]
@shubham-cmyk can you open a PR with short term goals (v0.1, stable api, etc...) and mid term goals ?

**Comment by shubham-cmyk** [comment]
PR or issues

**Comment by eddycharly** [comment]
A PR, just a ROADMAP.md file containing the roadmap (maybe drop a line in the README too).

**Comment by shubham-cmyk** [comment]
Okay
