### ISSUE TITLE
Create community docs page

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#538]
Create community docs page:
- Roadmap
- Slack channel
- Community meetings (when decided)

**Comment by shubhamku044** [comment]
I would like to take this issue

**Comment by eddycharly** [comment]
Thank you @shubhamku044 !

**Comment by eddycharly** [comment]
We use mkdocs to generate the docs from markdown, everything is in `website/docs`.
Ping us in the issue or in slack if you need any help.
