### ISSUE TITLE
Create a command to manage json schemas

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#613]
Create a command to manage json schemas from the CLI directly.

**Comment by shubham-cmyk** [comment]
Can you explain this a little

**Comment by eddycharly** [comment]
I though about something like `chainsaw install schemas ...` to copy json schemas locally. WDYT ?

**Comment by shubham-cmyk** [comment]
So saving the schemas into the ~/.chainsaw/

**Comment by eddycharly** [comment]
First step is to create the command to save the schemas on disk.

Adding docs to configure vscode is a good idea.

This will make using chainsaw in air gapped environments easier.
