### ISSUE TITLE
Create a form to add ADOPTERS

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#644]
Create a form to add ADOPTERS.

**Comment by jeremymv2** [comment]
I will say that I have been following kuttl and now this project seems to be even more promising for our teams.

**Comment by eddycharly** [comment]
Thanks @jeremymv2 !

As you know kuttl don't hesitate to share the limitations you faced using it if any. It will be super helpful to make the best decisions for Chainsaw :)

**Comment by eddycharly** [comment]
Closing, this is not important for now.
