### ISSUE TITLE
Rename generate command to build

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#680]
Rename generate command to build.

**Comment by webstradev** [comment]
Not worked with chainsaw before, but happy to pick this up

**Comment by eddycharly** [comment]
Thanks @webstradev !

I assigned it to you.

**Comment by webstradev** [comment]
Just one question is this only for `chainsaw generate` or also for `chainsaw generate docs`

**Comment by eddycharly** [comment]
Look in `pkg/commands/generate` this is what needs to be renamed.
Plus a couple of unit test related files.
