### ISSUE TITLE
Add a partial array check example

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#695]
Add a partial array check example.

**Comment by ankit-pn** [comment]
hey, I am new to open source and want to contribute to this issue. It would be great if you assign this to me and let me know how to get started!

**Comment by eddycharly** [comment]
Thanks for offering your help @ankit-pn !

You can do something similar to https://github.com/kyverno/chainsaw/blob/main/website/docs/examples/basic.md

**Comment by eddycharly** [comment]
@ankit-pn are you planning to work on this ?

**Comment by ankit-pn** [comment]
Yes, but since I am new to this I am not getting where to add those tests, it would be helpful if you provide some insight

**Comment by eddycharly** [comment]
@ankit-pn it's not about tests, just docs.

**Comment by ankit-pn** [comment]
can you pls specify where that partial array check test is available, so that get some info on it and then add the example of the same on docs?

**Comment by eddycharly** [comment]
Nothing ready to copy/paste, sorry.

**Comment by eddycharly** [comment]
Done in #715 

@ankit-pn you can familiarise with chainsaw and contribute to other issues.
