### ISSUE TITLE
[Feature] Support use of Chainsaw outside of Kubernetes

### ISSUE THREAD

**Issue by chipzoller** [kyverno/chainsaw#757]
### Problem Statement

Chainsaw is valuable enough that users may want to test for things like their own CLIs which have nothing to do with Kubernetes. Chainsaw would do well to support this without requiring a connection to a valid cluster.

### Solution Description

Support Chainsaw outside of Kubernetes. This should be simple with a switch which instructs it to not look for nor make a connection to a configured Kubernetes cluster.

### Slack discussion

https://kubernetes.slack.com/archives/C067LUFL43U/p1706136065726379

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
No, if the user specified that Chainsaw is running outside a cluster then any cluster- or Kubernetes-specific constructs and/or variables should not be set.

**Comment by chipzoller** [comment]
Great to see you added support for this so quickly!

**Comment by eddycharly** [comment]
@chipzoller consider it experimental, i will improve error management soon
