### ISSUE TITLE
[Feature] More information about the failed resource

### ISSUE THREAD

**Issue by vfarcic** [kyverno/chainsaw#775]
### Problem Statement

When testing child resources (e.g., a Pod created by a ReplicaSet created by a Deployment), it's hard to find out who the parent is from the output. Kuttl would provide full diff of both the actual and the desired resource definition. While the output in Kuttl is often confusing, it still provides an easier way to track down the parent resource than Chainsaw.

Here's an example:

```
devopstoolkitseries.com/v1alpha1/SQL/my-db-ncw5c - spec.id: Invalid value: "something": Expected value: "somethingxxx"
``` 

Since my tests spin up quite a few `my-db` resource, it's close to impossible to find out which one of those is the owner of `my-db-ncw5c` that is failing.

The report (JSON) helps with that problem, but it requires unnecessary steps to open it. I tend to run tests continuously in the background through a watcher and I'd prefer if the information is available in the output without having to open a separate file to deduce what's wrong.

### Solution Description

Provide a diff between the desired and the actual manifest in stdout.

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by eddycharly** [comment]
Thanks for your feedback.
I agree having a diff would be great, it's a lot harder to do than in kuttl though.

Is the use case about the diff or finding the parent ?

**Comment by vfarcic** [comment]
It's a bit of both. I definitely need to be able to find the parent, but I also find myself wanting to see both the desired and the actual resource. With Kuttl, I resolved quite a few issues detected through tests by, for example, looking at events of the resource that failed. With Chainsaw, I'd need to disable the deletion of resources so that I can inspect them manually or, in my case, spin the resource that is misbehaving outside tests (it's easier than having to delete everything spin up by tests manually).

**Comment by vfarcic** [comment]
If having a diff is complicated, outputting the resource that is being tested should do.

**Comment by eddycharly** [comment]
Ok, i'll try to come up with a solution to this.

I've been thinking about it multiple time and feel like there is a solution, maybe not a simple one but worth exploring.

**Comment by vfarcic** [comment]
That looks just about right

**Comment by eddycharly** [comment]
> That looks just about right

Cool, i need to fix a unit test and it will be in the next release.
