### ISSUE TITLE
[Bug]: Improve Error Handling in Discovery Folder

### ISSUE THREAD

**Issue by shubham-cmyk** [kyverno/chainsaw#805]
### chainsaw version Version

v0.1.0

### Description

If I pass the wrong path of the folder the chainsaw won't fail the test. 
Unit Test were also failing due to that. 

### Steps to reproduce

`make tests`

### Expected behavior

Chainsaw should throw error if the wrong non exist path is provided

### Logs

```Shell
--- FAIL: Test_Execute (44.60s)
    --- FAIL: Test_Execute/bad_folder (44.58s)
        command_test.go:71: 
            	Error Trace:	/home/opstree/chainsaw/pkg/commands/migrate/kuttl/tests/command_test.go:71
            	Error:      	An error is expected but got nil.
            	Test:       	Test_Execute/bad_folder
FAIL
coverage: 66.8% of statements
```

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by shubham-cmyk** [comment]
I think is should be considered a error otherwise we have to remove the unit Test that consider the wrong path as error

**Comment by eddycharly** [comment]
The unit test is actually testing permissions ;)

**Comment by shubham-cmyk** [comment]
okay then we have to create a temp directory with modified permission
