### ISSUE TITLE
[Feature] Check resource scope in describe collector

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#834]
### Problem Statement

Resource scope in describe collector is not taken into consideration (does not seem to cause issues though).

### Solution Description

Check resource scope in describe collector and ignore namespace if cluster scoped (or reject at validation time)

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by shubham-cmyk** [comment]
@eddycharly Should this be closed as discussed.

**Comment by eddycharly** [comment]
I think we can keep it.
