### ISSUE TITLE
[Feature] Add `--show-events` support in describe collector

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#835]
### Problem Statement

Add `--show-events` support in describe collector.

### Solution Description

Add `ShowEvents` field in describe struct and take it into consideration in the `collect` package.

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by shubham-cmyk** [comment]
@eddycharly events are already shown in the do you want to turn them off

**Comment by eddycharly** [comment]
> do you want to turn them off

yup, it's true by default but can be set to false.

```

    --show-events=true:
	If true, display events related to the described object.
```
