### ISSUE TITLE
[Feature] Implement programmatic validation for config

### ISSUE THREAD

**Issue by eddycharly** [kyverno/chainsaw#851]
### Problem Statement

We don't have programmatic validation for config (eg `namespaceModifiers`)

### Solution Description

Implement programmatic validation for config

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by shubham-cmyk** [comment]
i would take this

**Comment by eddycharly** [comment]
I started with this https://github.com/kyverno/chainsaw/pull/913 not sure what we want to validate though.
