### ISSUE TITLE
[Feature] Add --report-path to save the test report in a specified path.

### ISSUE THREAD

**Issue by IshwarKanse** [kyverno/chainsaw#930]
### Problem Statement

Tests in ephemeral or containerized environments need to persist test reports across job runs. KUTTL allows us to specify an --artifacts-dir. A similar parameter, --report-path, should be available in Chainsaw to designate the report saving path.
We use Prow CI for OpenTelemetry Operator and Tempo Operator tests, which run inside a Kubernetes pod. The --report-path will enable us to set a persistent volume path in the pod, preventing report deletion upon pod termination. See the CI job [script](https://github.com/openshift/release/blob/master/ci-operator/step-registry/distributed-tracing/tests/opentelemetry/distributed-tracing-tests-opentelemetry-commands.sh#L121) for reference.

### Solution Description

Add a parameter in Chainsaw to save the reports in a specified path. 

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by shubham-cmyk** [comment]
Currently the path is associated with the field `reportname` in the config like if you want the report to be generated at /root 
you can set the reportname to be `/root/chainsaw.report`

**Comment by eddycharly** [comment]
@shubham-cmyk do we support both relative and absolute paths in `reportName` ?

**Comment by shubham-cmyk** [comment]
No not the relative path this can be improved

**Comment by eddycharly** [comment]
Supporting a report path makes sense to me

**Comment by shubham-cmyk** [comment]
maybe we can split the name and the path

**Comment by shubham-cmyk** [comment]
current structure is something like this : 

```
func (report *TestsReport) SaveReportBasedOnType(reportFormat v1alpha1.ReportFormatType, reportName string) error {
	serializer, err := GetSerializer(reportFormat)
	if err != nil {
		return err
	}
	filePath := reportName + "." + strings.ToLower(string(reportFormat))
	return SaveReport(report, serializer, filePath)
}
```

```
func SaveReport(report *TestsReport, serializer ReportSerializer, filePath string) error {
	data, err := serializer.Serialize(report)
	if err != nil {
		return err
	}
	return os.WriteFile(filePath, data, 0o600)
}
```

**Comment by IshwarKanse** [comment]
@eddycharly @shubham-cmyk Thanks, I didn't know that report name also supports path. We can document that the path can also be added in the report name. https://kyverno.github.io/chainsaw/latest/configuration/reports/ and get the report name to also support relative path.

**Comment by eddycharly** [comment]
TBH i'm not against adding a report path config, sounds reasonable to me.

**Comment by IshwarKanse** [comment]
@eddycharly I have installed the v0.1.5 but the --report-path is not working. The report is stored in the same directory from where we are running Chainsaw. 

```
% cat .chainsaw.yaml 
# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/configuration-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: configuration
spec:
  parallel: 4
  timeouts:
    assert: 6m0s
    cleanup: 5m0s
    delete: 5m0s
    error: 5m0s
    apply: 10s


% mkdir /tmp/reports

%   chainsaw test \
  --report-name "dt-tests.xml" \
  --report-path "/tmp/reports" \
  --report-format "XML" \
  --test-dir \
  tests/e2e-acceptance 
Version: v0.1.5
No configuration provided but found default file: .chainsaw.yaml
Loading config (.chainsaw.yaml)...
- Using test file: chainsaw-test.yaml
- TestDirs [tests/e2e-acceptance]
- SkipDelete false
- FailFast false
- ReportFormat 'XML'
- ReportName 'dt-tests.xml'
- ReportPath '/tmp/reports'
- Namespace ''
- FullName false
- IncludeTestRegex ''
- ExcludeTestRegex ''
- ApplyTimeout 10s
- AssertTimeout 6m0s
- CleanupTimeout 5m0s
- DeleteTimeout 5m0s
- ErrorTimeout 5m0s
- ExecTimeout 5s
- Parallel 4
- NoCluster false
Loading tests...
- compatibility (tests/e2e-acceptance/compatibility)
- jaeger-otel-sidecar (tests/e2e-acceptance/jaeger-otel-sidecar)
- multitenancy (tests/e2e-acceptance/multitenancy)
- otlp-metrics-traces (tests/e2e-acceptance/otlp-metrics-traces)
- smoke-sidecar-other-namespace (tests/e2e-acceptance/smoke-sidecar-other-namespace)

    | 18:42:09 | smoke-sidecar-other-namespace | @cleanup | DELETE    | DONE  | v1/Namespace @ chainsaw-arriving-shiner
--- PASS: chainsaw (0.00s)
    --- PASS: chainsaw/otlp-metrics-traces (161.59s)
    --- PASS: chainsaw/jaeger-otel-sidecar (169.53s)
    --- PASS: chainsaw/multitenancy (178.09s)
    --- PASS: chainsaw/compatibility (179.43s)
    --- PASS: chainsaw/smoke-sidecar-other-namespace (63.47s)
PASS
Tests Summary...
- Passed  tests 5
- Failed  tests 0
- Skipped tests 0
Done.

% ls /tmp/reports 
% ls
Dockerfile		OWNERS			scripts
LICENSE			dt-tests.xml.xml	tests
```

**Comment by eddycharly** [comment]
Reopened, will investigate.

**Comment by shubham-cmyk** [comment]
@IshwarKanse Just tried I am not able to get produce the 

```
opstree@Latitude-3420:~$ ls
buildah         fake.json           opstree    trivy-operator
calcualte.bash  fake-py             Pictures   v2024.02.05.00.tar.gz
chainsaw        go                  Public     Videos
Desktop         id_rsa              shell_gpt  watchman-2024.02.05.00
Documents       mattermost-ansible  snap
Downloads       Music               Templates
fake-go         node_modules        testdata
opstree@Latitude-3420:~$ pwd
/home/opstree

```

`opstree@Latitude-3420:~/chainsaw$ ./chainsaw test --report-name=fake.json --report-path=/home/opstree --report-format="JSON" --test-dir testdata/e2e/examples/basic/`
