### ISSUE TITLE
Nix package [Feature] 

### ISSUE THREAD

**Issue by vfarcic** [kyverno/chainsaw#962]
### Problem Statement

It would be useful to have Chainsaw as a Nix package. Kyverno, for example, is already available.

### Solution Description

Create a Nix package

### Research

- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by Sanskarzz** [comment]
This is my understanding of the information provided. 
Nix is a package manager that allows reproducible and declarative package builds. Having Chainsaw available as a Nix package would make it easy to install and use with Nix. The process would involve writing a Nix expression that downloads the Chainsaw source code, compiles it, and bundles it into a Nix package. This could leverage the existing Makefile and build process. The Nix package would specify dependencies like Go and any other libraries needed to build Chainsaw. Nix can automatically fetch these dependencies. The end result would be a `chainsaw` derivation that users can easily install with `nix-env -iA nixpkgs.chainsaw` or use as a build input to other Nix packages and projects. 
The main Nixpkgs repository contains the Kyverno package definition [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/cluster/kyverno/default.nix)
Kyverno serves as a good example to follow when creating a Nix package for Chainsaw. The overall structure and build process will be very similar. 
I think i can create chainsaw nix package, can i try @eddycharly @vfarcic  ?

**Comment by eddycharly** [comment]
> can i try @eddycharly @vfarcic ?

it would be awesome ! ❤️

**Comment by eddycharly** [comment]
@Sanskarzz i would be interested to know if we have something to do to update the nix package when a new release is published, and if so how we can automate it 🙏

**Comment by vfarcic** [comment]
Let me give a bit of context behind this request.

I use something like https://github.com/vfarcic/crossplane-kubernetes/blob/main/shell.nix to define all the tool I need to work on a project. So, instead of having thousands of CLIs installed on my laptop, I just enter a repo I work on and execute `nix-shell` which creates an ephemeral environment with everything specified in `shell.nix`.

**Comment by Sanskarzz** [comment]
For kyverno nix package there is a [bot](https://github.com/NixOS/nixpkgs/commits?author=r-ryantm) i will take a look on that how we will use for chainsaw  

> @Sanskarzz i would be interested to know if we have something to do to update the nix package when a new release is published, and if so how we can automate it 🙏

**Comment by eddycharly** [comment]
I would be happy to have nix package support, i discovered nix recently and it looks great!
I just want to make sure it won't be a mess to maintain the package every time we cut a new release though 🤞.

**Comment by eddycharly** [comment]
@Sanskarzz assigned!

**Comment by Sanskarzz** [comment]
We need chainsaw vendor hash for nix. Currently their is no Go vendor for chainsaw branch v0.1.6. The vendor hash is dependent on which branch/commit of the repository you generate it from.

**Comment by eddycharly** [comment]
@Sanskarzz what is Go vendor ?

**Comment by Sanskarzz** [comment]
I have generated the vendor hash by myself now there is no need for you to generate. previously i was thinking something wrong i was thinking i don't have rights to generate it .
what is go vendor hash ?  
Go vendor is the Go dependency management system that copies all dependencies into a vendor/ folder in a project's source code and Nix needs to know when the dependencies in vendor/ change, so it can rebuild the package to incorporate the new dependencies and vendor hash allows Nix to efficiently track changes and rebuild only when necessary for Go packages with go vendor style dependency management. It captures the state of dependencies in a simple hash that can be compared across builds and it removes the need to re-build Go code when dependencies remain unchanged. Overall, it brings Go dependency management into line with Nix's declarative model . Currently i am also learning about it till now i have this much knowledge .
For more idea i have seen this [video](https://youtu.be/_HIM24JZoUs?si=vSuQ0FKT6wA-hj2t) for learning the go vendor

**Comment by eddycharly** [comment]
@Sanskarzz you mean vendoring our deps. Kyverno doesn't use vendoring and still, it is available as a nix package 🤔 

`kyverno-chainsaw` is fine.

**Comment by Sanskarzz** [comment]
> @Sanskarzz you mean vendoring our deps. Kyverno doesn't use vendoring and still, it is available as a nix package 🤔

Yes you are right, I was little confused previously .
Now to generate vendor hash i clone the kyverno/chainsaw repo and then i checkout v0.1.6 and applied this command `go mod vendor` and then to produce vendor hash i applied this command `nix-hash vendor/`

**Comment by Sanskarzz** [comment]
https://github.com/NixOS/nixpkgs/issues/291891

**Comment by Sanskarzz** [comment]
@eddycharly Please read [this](https://github.com/NixOS/nixpkgs/pull/291892#discussion_r1505382531)

**Comment by eddycharly** [comment]
What's up @Sanskarzz ?

**Comment by Sanskarzz** [comment]
Is it necessary to show list of adopter in chainsaw nix package ? There is no other nix package which show list of adopter of the package and if we want to show who are adopters of chainsaw we can add list to long description section but the nix maintainer will avoid avoid directly listing individual adopters in this package and would link to the project's [ADOPTERS.md](https://github.com/kyverno/chainsaw/blob/main/ADOPTERS.md) file. you can look what nix maintainer said about listing of package adopters at this [link](https://github.com/NixOS/nixpkgs/pull/291892#discussion_r1505382531) . 
what you think @eddycharly we have to add list of adopters to long description section or leave package without showing list of adopters ?

**Comment by eddycharly** [comment]
We don't care about the list of adopters. Keep it simple ;)

**Comment by Sanskarzz** [comment]
@eddycharly  Facing some error while reviewing chainsaw package in nix .
Can you investigate why the tests fail and what is needed to make them succeed?  form this [line](https://github.com/kyverno/chainsaw/blob/6a1928635c2aed3f260e01ea61d677f7ce06b730/pkg/commands/test/command_test.go#L170) the error pops up 
below are the log from running `nix run nixpkgs#nixpkgs-review -- pr --print-result 292144`.
```
sanskar@sanskar-HP-Laptop-15s-du1xxx:~/nixpkgs$ nix --extra-experimental-features nix-command --extra-experimental-features flakes run nixpkgs#nixpkgs-review -- pr --print-result 292144
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/292144/head:refs/nixpkgs-review/1
From https://github.com/NixOS/nixpkgs
   c932ac9d742b..469c3281a93b  master     -> refs/nixpkgs-review/0
$ git worktree add /home/sanskar/.cache/nixpkgs-review/pr-292144-1/nixpkgs 469c3281a93ba8f96fad9a790dd31cffb628937d
Preparing worktree (detached HEAD 469c3281a93b)
Updating files: 100% (40219/40219), done.
HEAD is now at 469c3281a93b Merge pull request #292455 from r-ryantm/auto-update/vintagestory
$ git merge --no-commit --no-ff a2f82f3c7290a4121815636ce0381ad322aa89f3
Auto-merging maintainers/maintainer-list.nix
Automatic merge went well; stopped before committing as requested
$ nix build --nix-path nixpkgs=/home/sanskar/.cache/nixpkgs-review/pr-292144-1/nixpkgs nixpkgs-overlays=/tmp/tmplmtdyjfh --extra-experimental-features nix-command no-url-literals --no-link --keep-going --no-allow-import-from-derivation --option build-use-sandbox relaxed -f /home/sanskar/.cache/nixpkgs-review/pr-292144-1/build.nix
error: builder for '/nix/store/5978ipvipk5ffp2dnkpprn2wcxqdd78i-kyverno-chainsaw-0.1.7.drv' failed with exit code 1;
       last 25 log lines:
       >         command_test.go:170:
       >                   Error Trace:    /build/source/pkg/commands/test/command_test.go:170
       >                    Error:          Not equal:
       >                                     expected: "Version: ---\nLoading default configuration...\n- Using test file: custom-test.yaml\n- TestDirs [.]\n- SkipDelete false\n- FailFast false\n- ReportFormat 'XML'\n- ReportName 'foo'\n- Namespace 'bar'\n- FullName true\n- IncludeTestRegex '^.*$'\n- ExcludeTestRegex '^.*$'\n- ApplyTimeout 1m40s\n- AssertTimeout 1m40s\n- CleanupTimeout 1m40s\n- DeleteTimeout 1m40s\n- ErrorTimeout 1m40s\n- ExecTimeout 1m40s\n- Parallel 24\n- RepeatCount 12\n- ForceTerminationGracePeriod 5s\n- NoCluster false\nLoading tests...\nLoading values...\nRunning tests...\nTests Summary...\n- Passed  tests 0\n- Failed  tests 0\n- Skipped tests 0\nDone.\n"
       >                              actual  : "Version: v0.1.7\nLoading default configuration...\n- Using test file: custom-test.yaml\n- TestDirs [.]\n- SkipDelete false\n- FailFast false\n- ReportFormat 'XML'\n- ReportName 'foo'\n- Namespace 'bar'\n- FullName true\n- IncludeTestRegex '^.*$'\n- ExcludeTestRegex '^.*$'\n- ApplyTimeout 1m40s\n- AssertTimeout 1m40s\n- CleanupTimeout 1m40s\n- DeleteTimeout 1m40s\n- ErrorTimeout 1m40s\n- ExecTimeout 1m40s\n- Parallel 24\n- RepeatCount 12\n- ForceTerminationGracePeriod 5s\n- NoCluster false\nLoading tests...\nLoading values...\nRunning tests...\n"
       >
       >                                    Diff:
       >                                  --- Expected
       >                                   +++ Actual
       >                                     @@ -1,2 +1,2 @@
       >                                -Version: ---
       >                                  +Version: v0.1.7
       >                                Loading default configuration...
       >                              @@ -25,7 +25,2 @@
       >                               Running tests...
       >                              -Tests Summary...
       >                              -- Passed  tests 0
       >                                     -- Failed  tests 0
       >                                     -- Skipped tests 0
       >                                     -Done.
       >
       >                Test:           TestChainsawCommand/all_flags
       > FAIL
       > FAIL       github.com/kyverno/chainsaw/pkg/commands/test   0.363s
       > FAIL
       For full logs, run 'nix-store -l /nix/store/5978ipvipk5ffp2dnkpprn2wcxqdd78i-kyverno-chainsaw-0.1.7.drv'.
error: 1 dependencies of derivation '/nix/store/23hy6r508cp48x978vw4nxa0dmax2vrp-review-shell.drv' failed to build

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/292144

1 package failed to build:
kyverno-chainsaw

warning: error: unable to download 'https://cache.nixos.org/nix-cache-info': Couldn't resolve host name (6); retrying in 299 ms
warning: error: unable to download 'https://cache.nixos.org/nix-cache-info': Couldn't resolve host name (6); retrying in 608 ms
warning: error: unable to download 'https://cache.nixos.org/nix-cache-info': Couldn't resolve host name (6); retrying in 1297 ms
warning: error: unable to download 'https://cache.nixos.org/nix-cache-info': Couldn't resolve host name (6); retrying in 2466 ms
warning: unable to download 'https://cache.nixos.org/nix-cache-info': Couldn't resolve host name (6)
Result of `nixpkgs-review pr 292144` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>kyverno-chainsaw</li>
  </ul>
</details>

$ /nix/store/62fm7r6175k2bgvhc19hn9bdhw90wa3n-nix-2.18.1/bin/nix-shell /home/sanskar/.cache/nixpkgs-review/pr-292144-1/shell.nix --nix-path nixpkgs=/home/sanskar/.cache/nixpkgs-review/pr-292144-1/nixpkgs nixpkgs-overlays=/tmp/tmplmtdyjfh
warning: error: unable to download 'https://cache.nixos.org/vmgwn3xsbyj860z2bazvg4n10c4kp3xk.narinfo': Couldn't resolve host name (6); retrying in 316 ms
warning: error: unable to download 'https://cache.nixos.org/vmgwn3xsbyj860z2bazvg4n10c4kp3xk.narinfo': Couldn't resolve host name (6); retrying in 617 ms
warning: error: unable to download 'https://cache.nixos.org/vmgwn3xsbyj860z2bazvg4n10c4kp3xk.narinfo': Couldn't resolve host name (6); retrying in 1097 ms
warning: error: unable to download 'https://cache.nixos.org/vmgwn3xsbyj860z2bazvg4n10c4kp3xk.narinfo': Couldn't resolve host name (6); retrying in 2490 ms
error: unable to download 'https://cache.nixos.org/vmgwn3xsbyj860z2bazvg4n10c4kp3xk.narinfo': Couldn't resolve host name (6)
$ git worktree remove -f /home/sanskar/.cache/nixpkgs-review/pr-292144-1/nixpkgs
```

**Comment by eddycharly** [comment]
@Sanskarzz why are unit tests executed ?

**Comment by Sanskarzz** [comment]
Nix fetches from package from github when building a Nix package, unit tests are executed as part of the build process to ensure the correctness and reliability of the package. 
Is it necessary to add this unit test in build process? if we don't want to add unit test in build process than we can add `doCheck = false` in nix script so it will neglect/NOTRUN unit test in build process . WDYT ?

**Comment by vfarcic** [comment]
Kyverno Chainsaw is already tested so I'm not sure there would be much value in testing it again using the same tests. If anything, you might want to test whether the Nix package was created correctly, but not whether the Chainsaw code passes the same tests it already passed.

**Comment by eddycharly** [comment]
Closing, PR on nixpkgs repo was merged.

**Comment by vfarcic** [comment]
@Sanskarzz any idea when it might appear in https://search.nixos.org? I'm a heavy Nix user but I haven't published a package so I'm not sure how it works. Will it be created with the next Chainsaw release?

**Comment by eddycharly** [comment]
@vfarcic i asked one of the maintainers and he told me it takes 2 or 3 days 🤷
